name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [django42, quality, docs, pii_check]

    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Install Dependencies
        run: pip install -r requirements/ci.txt

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

 # Disabled: until this can be resolved: https://twou.slack.com/archives/C044520P010/p1712756140233839
      - name: Run coverage
        if: matrix.python-version == '3.8' && matrix.toxenv == 'django42'
        uses: codecov/codecov-action@v1
        continue-on-error: true
        with:
          flags: unittests
          fail_ci_if_error: false
