name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
        toxenv: [django42, quality, docs, pii_check]
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Remove cached pip and tox environments
        run: |
          pip cache purge || true
          rm -rf .tox

      - name: Install Dependencies
        run: pip install -r requirements/ci.txt

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

      - name: Report coverage
        id: coverage_comment
        if: matrix.python-version == '3.12' && matrix.toxenv == 'django42'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 85
          ANNOTATE_MISSING_LINES: true
          ANNOTATION_TYPE: error

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
          name: python-coverage-comment-action
          # If you use a different name, update COMMENT_FILENAME accordingly
          path: python-coverage-comment-action.txt
