name: Upgrade Python Requirements

on:
  schedule:
    # Monthly on the first of the month at 00:00 UTC.
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch against which to create requirements PR"
        required: true
        default: 'main'

jobs:


  call-upgrade-python-requirements-workflow:

    uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@master

    with:
      branch: ${{ github.event.inputs.branch || "main" }}
      user_reviewers: edx-revenue-tasks
      team_reviewers: ""
      email_address: revenue-tasks@edx.org
      send_success_notification: false

    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}


  call-upgrade-python-requirements-workflow-develop:

    # Unless called for a specific branch, run on the develop branch too.
    if: github.event.inputs.branch == ""

    uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@master

    with:
      branch: develop
      user_reviewers: edx-revenue-tasks
      team_reviewers: ""
      email_address: revenue-tasks@edx.org
      send_success_notification: false

    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
